### ISSUE TITLE
support system wide / user installation 

### ISSUE THREAD

**Issue by blshkv** [P0cL4bs/wifipumpkin3#189]
Basically, revert https://github.com/P0cL4bs/wifipumpkin3/commit/b082f0d66f8c03c2e9711f3c99c77c562be4403e. That commit broke it.

This is a common problem that many tools which we want to distribute do not support system wide installation. Some of these tools provide their own "install.sh" or "setup.sh" with a distro specific commands (sudo apt-install) to install dependencies instead of a proper setup.py/pyproject.toml (PEP 517).
With a proper setup.py script, an end user can install it using the following single command:
python3 setup.py install --user. It also a distro friendly and makes life for maintainers easier.

The end result, a FHS compliant directory structure should be created.
In case if software produce any output, a local user directory should be used, such as ```~./<software>/```

There are some custom cases (installing non-python packages, data files etc) which have been resolved in other packages. Bellow, are reference points on such bug reports with solutions (patches)
https://github.com/pentoo/pentoo-overlay/issues/596

```
 * ACCESS DENIED:  mkdir:         /usr/share/wifipumpkin3
Traceback (most recent call last):
  File "/var/tmp/portage/net-wireless/wifipumpkin3-1.1.3_p1/work/wifipumpkin3-1.1.3-R1/setup.py", line 51, in <module>
    create_user_dir_config()
  File "/var/tmp/portage/net-wireless/wifipumpkin3-1.1.3_p1/work/wifipumpkin3-1.1.3-R1/setup.py", line 44, in create_user_dir_config
    os.makedirs(user_config_dir, exist_ok=True)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/share/wifipumpkin3'
 * ERROR: net-wireless/wifipumpkin3-1.1.3_p1::pentoo failed (compile phase):

```

**Comment by blshkv** [comment]
also:
```
 * QA Notice: setuptools warnings detected:
 * 
 *          Installing 'wifipumpkin3.plugins.pumpkinproxy.tmp' as data is deprecated, please list it in `packages`.
 *          Installing 'wifipumpkin3.plugins.pumpkinproxy.tmp.doc' as data is deprecated, please list it in `packages`.
 *          Installing 'wifipumpkin3.plugins.pumpkinproxy.tmp.exe' as data is deprecated, please list it in `packages`.
 *          Installing 'wifipumpkin3.plugins.pumpkinproxy.tmp.pdf' as data is deprecated, please list it in `packages`.
 *          Installing 'wifipumpkin3.plugins.pumpkinproxy.tmp.xls' as data is deprecated, please list it in `packages`.
```

**Comment by mh4x0f** [comment]
This settings is required because the wp3 not should be installed using --user mode because when do this the wp3 will be create a folder on {user}/.config but wp3 require run as super user this change the config to {root}/.config this is a problem for me. make a debian package need to be create a folder on /usr/share/wifipumpkin3 with all files for settings of wp3. as you can see on installation page of wp3 i recommended to install as super user because because wp require super user for run. I can't revert it this is solve make problem with installation of new plugins and solve problem to create a debian package.

**Comment by mh4x0f** [comment]
my recommendation for you is create a fork of wp3 and do your settings for your system because i only support the debian, i'm only test on debian.

**Comment by blshkv** [comment]
you are doing it wrong even for debian. NO tools should write anything into system folders such as /usr/share
What is the problem with using root/.config?

**Comment by blshkv** [comment]
I guess for configs and plugins you can use a standard setup mechanism: 
https://github.com/mschwager/fierce/issues/25#issuecomment-360003002
data_files OR package_data OR packages

**Comment by blshkv** [comment]
just to be clear, user_config_dir should stay as it was before, all output and user's data should be written there.
config_dir should be your packages=[] with system configs, plugins etc

**Comment by mh4x0f** [comment]
okay, I 'm find a possible solution your problem is install on `/usr/share/` and run `python3 setup.py install --user` correct ?

**Comment by mh4x0f** [comment]
I pushed non `draft-configdir` a patch for solve this problem check out and send me the feedback.

**Comment by blshkv** [comment]
ok, I'm testing 1.1.3 R2, and hit an unrelated bug:
```
 * QA Notice: The ebuild is installing to one or more unexpected paths:
 * 
 *   /usr/wifipumpkin3
 * 
 * Please fix the ebuild to use correct FHS/Gentoo policy paths.

```

**Comment by blshkv** [comment]
https://github.com/P0cL4bs/wifipumpkin3/issues/189#issuecomment-1173005649
That bug is still not fixed. Could you have a look since we are on it?

**Comment by blshkv** [comment]
Also, the tool does not run for me. Any ideas?

```
bash$ sudo -E wifipumpkin3 
/usr/lib/python3.10/site-packages/scapy/layers/ipsec.py:471: CryptographyDeprecationWarning: Blowfish has been deprecated
  cipher=algorithms.Blowfish,
/usr/lib/python3.10/site-packages/scapy/layers/ipsec.py:485: CryptographyDeprecationWarning: CAST5 has been deprecated
  cipher=algorithms.CAST5,
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.10/wifipumpkin3", line 33, in <module>
    sys.exit(load_entry_point('wifipumpkin3==1.1.3', 'console_scripts', 'wifipumpkin3')())
  File "/usr/lib/python3.10/site-packages/wifipumpkin3/__main__.py", line 86, in main
    config.set("accesspoint", "status_ap", False)
  File "/usr/lib/python3.10/site-packages/wifipumpkin3/core/utility/collection.py", line 47, in set
    self.psettings.beginGroup(name_group)
AttributeError: 'SettingsINI' object has no attribute 'psettings'
```

**Comment by mh4x0f** [comment]
no problem check if work fine now I 'll make a release after that

**Comment by blshkv** [comment]
yeap, seems fixed. Thanks

**Comment by mh4x0f** [comment]
great work brow, thanks for support
